site_name: iumiCash REST API

theme:
  logo: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features:
    - navigation.expand
    - navigation.instant
#    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - search.suggest
    - search.highlight

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago


extra_css:
  - assets/css/style.css

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Getting started: token.md
  - Requests: requests.md
  - Responses: responses.md
  - Authentication:
      - Authentication - Introduction: authentication/index.md
      - Generate access token: authentication/token.md
      - Authorization code request: authentication/authorize.md
  - Vendors:
      - Vendors - Introduction: vendors/token.md
      - Registration: vendors/vendor_registration.md
      - Verification: vendors/verification.md
      - Development page: vendors/development_page.md
  - Orders:
      - Orders: orders/token.md
      - Create order: orders/create_order.md
      - Capture order: orders/capture.md
      - Recurrent payments: orders/recurrent_payment.md
      - Callback: orders/callback.md
  - Flow diagrams:
      - Payment: diagrams/onetime.md
      - Recurrent payment: diagrams/recurrent.md
  - Idempotency: idempotency.md
