site_name: iumiCash REST API

theme:
  logo: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  name: material
  features:
    - navigation.expand
    - navigation.instant
#    - navigation.indexes
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.annotate
    - content.tooltips
    - content.tabs.link
    - search.suggest
    - search.highlight

markdown_extensions:
  - def_list
  - admonition
  - tables
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago


extra_css:
  - assets/css/style.css


nav:
  - Getting started: index.md
  - Authentication: authentication/index.md
  - Requests: requests.md
  - Responses: responses.md
  - Vendors:
      - Vendors - Introduction: vendors/index.md
      - Registration: vendors/vendor_registration.md
      - Verification: vendors/verification.md
      - User settings : vendors/settings.md
      - Development page: vendors/development_page.md
  - Orders:
      - Orders: orders/index.md
      - Create order: orders/create_order.md
      - Recurrent payments: orders/recurrent_payment.md
      - Callback: orders/callback.md
  - Flow diagrams:
      - One-Time payment: diagrams/onetime.md
      - Recurrent payment: diagrams/recurrent.md
  - Idempotency: idempotency.md
